-- Populate aliases for parent company -> consumer brand mappings

update ktc_assessments set aliases = '{"Zara","Pull&Bear","Massimo Dutti","Bershka","Stradivarius","Oysho","Zara Home"}' where brand = 'Industria de Diseño Textil SA (Inditex)';
update ktc_assessments set aliases = '{"H&M","COS","Monki","Weekday","& Other Stories","ARKET"}' where brand = 'Hennes & Mauritz AB (H&M)';
update ktc_assessments set aliases = '{"Uniqlo","GU","Theory","Helmut Lang"}' where brand = 'Fast Retailing Co. Ltd.';
update ktc_assessments set aliases = '{"Versace","Jimmy Choo","Michael Kors"}' where brand = 'Capri Holdings Ltd.';
update ktc_assessments set aliases = '{"Coach","Kate Spade","Stuart Weitzman"}' where brand = 'Tapestry Inc.';
update ktc_assessments set aliases = '{"Calvin Klein","Tommy Hilfiger","Warner''s","Olga"}' where brand = 'PVH Corp.';
update ktc_assessments set aliases = '{"The North Face","Vans","Timberland","Dickies","Supreme"}' where brand = 'VF Corp.';
update ktc_assessments set aliases = '{"Gucci","Saint Laurent","Bottega Veneta","Balenciaga","Alexander McQueen","Brioni"}' where brand = 'Kering SA';
update ktc_assessments set aliases = '{"Louis Vuitton","Dior","Fendi","Givenchy","Marc Jacobs","Loewe","Celine"}' where brand = 'LVMH Moet Hennessy Louis Vuitton SE';
update ktc_assessments set aliases = '{"Hanes","Champion","Bonds","Bali","Playtex","L''eggs"}' where brand = 'Hanesbrands Inc.';
update ktc_assessments set aliases = '{"Gildan","American Apparel","Comfort Colors","GOLDTOE"}' where brand = 'Gildan Activewear Inc.';
update ktc_assessments set aliases = '{"Gap","Old Navy","Banana Republic","Athleta"}' where brand = 'Gap Inc.';
update ktc_assessments set aliases = '{"Yoshida","Wealthplus"}' where brand = 'Pou Chen Corp.';
update ktc_assessments set aliases = '{"Renner","Camicado","Youcom"}' where brand = 'Lojas Renner SA';
update ktc_assessments set aliases = '{"JD Sports","Finish Line","DTLR"}' where brand = 'JD Sports Fashion plc';
update ktc_assessments set aliases = '{"MUJI"}' where brand = 'Ryohin Keikaku Co. Ltd.';
update ktc_assessments set aliases = '{"UGG","HOKA","Teva","Sanuk","Koolaburra"}' where brand = 'Deckers Outdoor Corp.';
update ktc_assessments set aliases = '{"Columbia","SOREL","Mountain Hardwear","prAna"}' where brand = 'Columbia Sportswear Co.';
update ktc_assessments set aliases = '{"Carter''s","OshKosh B''gosh","Skip Hop"}' where brand = 'Carter''s Inc.';
update ktc_assessments set aliases = '{"Ferragamo"}' where brand = 'Salvatore Ferragamo SpA';
update ktc_assessments set aliases = '{"BOSS","HUGO"}' where brand = 'Hugo Boss AG';
update ktc_assessments set aliases = '{"Moncler","Stone Island"}' where brand = 'Moncler SpA';
update ktc_assessments set aliases = '{"Kohl''s"}' where brand = 'Kohl''s Corp.';
update ktc_assessments set aliases = '{"Dick''s Sporting Goods","Golf Galaxy","Public Lands"}' where brand = 'Dick''s Sporting Goods Inc.';
update ktc_assessments set aliases = '{"Foot Locker","Kids Foot Locker","Champs Sports","WSS"}' where brand = 'Foot Locker Inc.';
update ktc_assessments set aliases = '{"boohoo","PrettyLittleThing","Nasty Gal","MissPap","Karen Millen","Coast","Warehouse","Oasis"}' where brand = 'boohoo group Plc';
update ktc_assessments set aliases = '{"TJ Maxx","Marshalls","HomeGoods","Winners","HomeSense"}' where brand = 'The TJX Companies Inc.';
update ktc_assessments set aliases = '{"Macy''s","Bloomingdale''s","Bluemercury"}' where brand = 'Macy''s Inc.';
update ktc_assessments set aliases = '{"Ralph Lauren","Polo Ralph Lauren","Lauren Ralph Lauren","Chaps","Club Monaco"}' where brand = 'Ralph Lauren Corp.';
update ktc_assessments set aliases = '{"Levi''s","Dockers","Denizen"}' where brand = 'Levi Strauss & Co.';
update ktc_assessments set aliases = '{"Under Armour"}' where brand = 'Under Armour Inc.';
update ktc_assessments set aliases = '{"Skechers"}' where brand = 'Skechers U.S.A. Inc.';
update ktc_assessments set aliases = '{"American Eagle","Aerie","Offline"}' where brand = 'American Eagle Outfitters Inc.';
update ktc_assessments set aliases = '{"Puma"}' where brand = 'Puma SE';
update ktc_assessments set aliases = '{"Adidas","Reebok"}' where brand = 'Adidas AG';
update ktc_assessments set aliases = '{"Nike","Jordan","Converse"}' where brand = 'Nike Inc.';
update ktc_assessments set aliases = '{"Lululemon","lululemon"}' where brand = 'Lululemon Athletica Inc.';
update ktc_assessments set aliases = '{"Burberry"}' where brand = 'Burberry Group plc';
update ktc_assessments set aliases = '{"Next"}' where brand = 'Next plc';
update ktc_assessments set aliases = '{"ASOS"}' where brand = 'ASOS Plc';
update ktc_assessments set aliases = '{"Primark","Penneys"}' where brand = 'Primark';
update ktc_assessments set aliases = '{"ASICS"}' where brand = 'Asics Corp.';
update ktc_assessments set aliases = '{"Canada Goose"}' where brand = 'Canada Goose Holdings Inc.';
update ktc_assessments set aliases = '{"Aritzia","Wilfred","TNA"}' where brand = 'Aritzia, Inc.';
update ktc_assessments set aliases = '{"Walmart","Walmart.ca","George"}' where brand = 'Walmart Inc.';
update ktc_assessments set aliases = '{"Amazon","Amazon Fashion","Amazon.ca"}' where brand = 'Amazon.com Inc.';
update ktc_assessments set aliases = '{"Zalando"}' where brand = 'Zalando';